### PR TITLE
Recipt fix

### LINKED ISSUE #66: recipt only have 1 item per person

### PR DESCRIPTION
**Pull request by ddnowicki**

### CODE REVIEW

File: src/core/reciptOperations.cpp [hunk 1]
```diff
@@ -6,25 +6,32 @@ std::vector<User> ReciptOperations::calculateReceipt(
     const std::vector<Item>& items) const {
   std::vector<User> users;
```
Comment (patkaczm) [inline src/core/reciptOperations.cpp:7]: Is `users` ever filled?

File: src/core/reciptOperations.cpp [hunk 2]
```diff
@@ -6,25 +6,32 @@ std::vector<User> ReciptOperations::calculateReceipt(
...
 
-  for (auto item : items) {
+  for (const auto& item : items) {
     int cost = item.price * item.amount;
     bool foundEqualUserID = false;
-    for (auto user : users) {
+
+    if (!database.isThereUserWithThisID(item.whoBuy)) {
+      std::vector<User> usersNull;
```
Comment (patkaczm) [inline src/core/reciptOperations.cpp]: you could just `return {}`

File: src/core/reciptOperations.cpp [hunk 3]
```diff
@@ -6,25 +6,32 @@ std::vector<User> ReciptOperations::calculateReceipt(
...
+      return usersNull;
+    }
+    
+    for (auto& user : users) {
```
Comment (patkaczm) [inline src/core/reciptOperations.cpp:16]: you could use `std::find`

**Review by patkaczm — APPROVED** [review]
